#! /bin/bash

set -e

if [ "${UID}" != "0" ]; then
	echo "artixinstall: requires root permissions"
	exit 1
fi

pacman -Sy
pacman -S --needed --noconfirm parted

parted -s /dev/sda mklabel msdos
parted -s -a optimal /dev/sda mkpart primary ext4 0% 256MiB
parted -s -a optimal /dev/sda mkpart primary btrfs 256MiB 100%

mkfs.ext4 -F -L BOOT /dev/sda1
mkfs.btrfs -f /dev/sda2

mkdir /btrfs
mount -o compress=zstd /dev/sda2 /btrfs
btrfs subvolume create /btrfs/root
umount /btrfs

mount -o compress=zstd,subvol=/root /dev/sda2 /mnt
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot

rc-service ntpd start

basestrap /mnt base base-devel openrc elogind-openrc vim man ntp ntp-openrc git
basestrap /mnt linux linux-firmware

artix-chroot /mnt bash -c 'curl -fsSL https://raw.githubusercontent.com/HimbeerserverDE/artixinstall/main/mkartix | bash'

fstabgen -U /mnt >> /mnt/etc/fstab

umount -R /mnt

echo -e "\n\e[1m\e[1;32mArtix has been successfully installed! It is now safe to reboot."
echo -e "\e[1m\e[1;32mDon't forget to change the root password and hostname."
echo -en "\e[0m"
