#! /bin/bash

set -e

if [ "${UID}" != "0" ]; then
	echo "artixinstall: requires root permissions"
	exit 1
fi

pacman -Sy
pacman -S --needed --noconfirm parted fzf

#
# Config questions
#

DRIVE=$1
TARGET=$2

if [ -z "${DRIVE}" ]; then
	DRIVE="/dev/$(lsblk | grep disk | fzf --disabled | awk '{print $1}')"
fi

if [[ "${DRIVE}" == "/dev/mmcblk"* ]] | [[ "${DRIVE}" == "/dev/nvme"* ]]; then
	PART_PREFIX="${DRIVE}p"
else
	PART_PREFIX="${DRIVE}"
fi

if [ -z "${TARGET}" ]; then
	echo -en "\e[1m\e[1;33mEnter GRUB target (commonly i386-pc): "
	read TARGET

	echo -e "\e[0m"
fi

# Needed because otherwise the disk might be overwritten
# without installing a bootable system.
if [ -z "${TARGET}" ]; then
	echo -e "\e[1m\e[1;31mGRUB target must not be empty.\e[0m"
	exit 1
fi

parted -s ${DRIVE} mklabel msdos
parted -s -a optimal ${DRIVE} mkpart primary ext4 0% 256MiB
parted -s -a optimal ${DRIVE} mkpart primary btrfs 256MiB 100%

mkfs.ext4 -F -L BOOT ${PART_PREFIX}1
mkfs.btrfs -f ${PART_PREFIX}2

mkdir /btrfs
mount -o compress=zstd ${PART_PREFIX}2 /btrfs
btrfs subvolume create /btrfs/root
umount /btrfs

mount -o compress=zstd,subvol=/root ${PART_PREFIX}2 /mnt
mkdir /mnt/boot
mount ${PART_PREFIX}1 /mnt/boot

rc-service ntpd start

basestrap /mnt base base-devel openrc elogind-openrc vim man ntp ntp-openrc git
basestrap /mnt linux linux-firmware

artix-chroot /mnt bash -c "curl -fsSL https://raw.githubusercontent.com/HimbeerserverDE/artixinstall/main/mkartix | sh -s -- ${DRIVE} ${PART_PREFIX} ${TARGET}"

fstabgen -U /mnt >> /mnt/etc/fstab

umount -R /mnt

echo -e "\n\e[1m\e[1;32mArtix has been successfully installed! It is now safe to reboot."
echo -e "\e[1m\e[1;32mDon't forget to change the root password and hostname."
echo -e "\e[1m\e[1;32mSetting up networking is left to you, dhcpcd and wpa_supplicant are installed."
echo -en "\e[0m"
