#! /bin/bash

set -e

if [ "${UID}" != "0" ]; then
	echo "artixinstall: requires root permissions"
	exit 1
fi

pacman -Sy --noconfirm parted

#
# Full Disk Encryption
#

parted -s /dev/sda mklabel msdos
parted -s -a optimal /dev/sda mkpart primary ext4 0% 256MiB
parted -s -a optimal /dev/sda mkpart primary ext4 256MiB 100%

echo "artix" | cryptsetup -q luksFormat /dev/sda2
echo "artix" | cryptsetup -q open /dev/sda2 sda2_crypt

mkfs.fat -F -L BOOT /dev/sda1
mkfs.btrfs -f /dev/mapper/sda2_crypt

mount /dev/mapper/sda2_crypt /mnt
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot

#
# Continue Installation
#

rc-service ntpd start

basestrap /mnt base base-devel openrc elogind-openrc
basestrap /mnt linux linux-firmware

artix-chroot /mnt bash -c 'curl https://raw.githubusercontent.com/HimbeerserverDE/artixinstall/main/mkcryptartix | bash'

fstabgen -U /mnt >> /mnt/etc/fstab

umount -R /mnt
cryptsetup -q close sda2_crypt

echo "Artix has been successfully installed! It is now safe to reboot."
