#! /bin/bash

set -e

if [ "${UID}" != "0" ]; then
	echo "cryptinstall: requires root permissions"
	exit 1
fi

pacman -Sy
pacman -S --needed --noconfirm parted fzf

#
# Config questions
#

DRIVE=$1

if [ -z "${DRIVE}" ]; then
	DRIVE="/dev/$(lsblk | grep disk | fzf --disabled | awk '{print $1}')"
fi

if [[ "${DRIVE}" == "/dev/mmcblk"* ]] | [[ "${DRIVE}" == "/dev/nvme"* ]]; then
	PART_PREFIX="${DRIVE}p"
else
	PART_PREFIX="${DRIVE}"
fi

#
# Full Disk Encryption
#

parted -s ${DRIVE} mklabel msdos
parted -s -a optimal ${DRIVE} mkpart primary ext4 0% 256MiB
parted -s -a optimal ${DRIVE} mkpart primary ext4 256MiB 100%

echo "artix" | cryptsetup -q --pbkdf pbkdf2 luksFormat ${PART_PREFIX}1
echo "artix" | cryptsetup -q open ${PART_PREFIX}1 boot_crypt

echo "artix" | cryptsetup -q luksFormat ${PART_PREFIX}2
echo "artix" | cryptsetup -q open ${PART_PREFIX}2 root_crypt

mkfs.ext4 -F -L BOOT /dev/mapper/boot_crypt
mkfs.btrfs -f /dev/mapper/root_crypt

mkdir /btrfs
mount -o compress=zstd /dev/mapper/root_crypt /btrfs
btrfs subvolume create /btrfs/root
umount /btrfs

mount -o compress=zstd,subvol=/root /dev/mapper/root_crypt /mnt
mkdir /mnt/boot
mount /dev/mapper/boot_crypt /mnt/boot

#
# Continue Installation
#

rc-service ntpd start

basestrap /mnt base base-devel openrc elogind-openrc vim man ntp ntp-openrc git
basestrap /mnt linux linux-firmware

artix-chroot /mnt bash -c "curl -fsSL https://raw.githubusercontent.com/HimbeerserverDE/artixinstall/main/mkcryptartix | sh -s -- ${DRIVE} ${PART_PREFIX}"

fstabgen -U /mnt >> /mnt/etc/fstab

umount -R /mnt

cryptsetup -q close boot_crypt
cryptsetup -q close root_crypt

echo -e "\n\e[1m\e[1;32mArtix has been successfully installed! It is now safe to reboot."
echo -e "\e[1m\e[1;32mDon't forget to change the root password, disk passwords and hostname."
echo -e "\e[1m\e[1;32mSetting up networking is left to you."
echo -e "\n\e[1m\e[1;32mRun the following commands to change the disk passwords:"
echo -e "\e[1m\e[1;32m\t# cryptsetup --pbkdf pbkdf2 luksChangeKey ${PART_PREFIX}1"
echo -e "\e[1m\e[1;32m\t# cryptsetup luksChangeKey ${PART_PREFIX}2"
echo -e "\n\e[1m\e[1;32mChoose US compatible passwords as GRUB uses the US keyboard layout."
echo -en "\e[0m"
