#! /bin/bash

set -e

if [ "${UID}" != "0" ]; then
	echo "artixinstall: requires root permissions"
	exit 1
fi

pacman -Sy
pacman -S --needed --noconfirm parted

#
# Full Disk Encryption
#

parted -s /dev/sda mklabel msdos
parted -s -a optimal /dev/sda mkpart primary ext4 0% 256MiB
parted -s -a optimal /dev/sda mkpart primary ext4 256MiB 100%

echo "artix" | cryptsetup -q --hash pbkdf2 luksFormat /dev/sda1
echo "artix" | cryptsetup -q open /dev/sda1 sda1_crypt

echo "artix" | cryptsetup -q luksFormat /dev/sda2
echo "artix" | cryptsetup -q open /dev/sda2 sda2_crypt

mkfs.ext4 -F -L BOOT /dev/mapper/sda1_crypt
mkfs.btrfs -f /dev/mapper/sda2_crypt

mkdir /btrfs
mount -o compress=zstd /dev/mapper/sda2_crypt /btrfs
btrfs subvolume create /btrfs/root
umount /btrfs

mount -o compress=zstd,subvol=/root /dev/mapper/sda2_crypt /mnt
mkdir /mnt/boot
mount /dev/mapper/sda1_crypt /mnt/boot

#
# Continue Installation
#

rc-service ntpd start

basestrap /mnt base base-devel openrc elogind-openrc vim ntp ntp-openrc
basestrap /mnt linux linux-firmware

artix-chroot /mnt bash -c 'curl -fsSL https://raw.githubusercontent.com/HimbeerserverDE/artixinstall/main/mkcryptartix | bash'

fstabgen -U /mnt >> /mnt/etc/fstab

umount -R /mnt
cryptsetup -q close sda2_crypt

echo "Artix has been successfully installed! It is now safe to reboot."
