#! /bin/bash

set -e

#
# Config questions
#

TIMEZONE=$1
KEYMAP=$2

if [ -z "${TIMEZONE}" ]; then
	TIMEZONE=$(find /usr/share/zoneinfo | fzf)
fi

if [ -z "${KEYMAP}" ]; then
	KEYMAP=$(echo "Enter keymap (e.g. us, de): " | fzf --disabled --print-query | sed -n '1 p')
fi

pacman -Syu --noconfirm

rc-service ntpd start

ln -sf "/usr/share/zoneinfo/${TIMEZONE}" /etc/localtime

sed -i "s/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/" /etc/locale.gen
locale-gen

cat <<EOT > /etc/locale.conf
export LANG="en_US.UTF-8"
export LC_COLLATE="C"
EOT

sed -i "s/keymap=\"us\"/keymap=\"${KEYMAP}\"/" /etc/conf.d/keymaps

pacman -Sy --needed --noconfirm btrfs-progs

# Network
## Hostname
echo armtix > /etc/hostname

cat <<EOT > /etc/hosts
# Static table lookup for hostnames.
# See hosts(5) for details.

127.0.0.1	localhost
127.0.1.1	armtix.local armtix

# IPv6
::1		localhost	ip6-localhost	ip6-loopback
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
EOT

sed -i 's/hostname="localhost"/hostname="armtix"/' /etc/conf.d/hostname

## Networking essentials
pacman -Sy --needed --noconfirm dhcpcd wpa_supplicant

# Repositories
## Arch
pacman -Sy --needed --noconfirm artix-archlinux-support

cat <<EOT >> /etc/pacman.conf

#
# Custom
#

# Arch

#[testing]
#Include = /etc/pacman.d/mirrorlist-archlinuxarm

[extra]
Include = /etc/pacman.d/mirrorlist-archlinuxarm

#[community-testing]
#Include = /etc/pacman.d/mirrorlist-archlinuxarm

[community]
Include = /etc/pacman.d/mirrorlist-archlinuxarm

#[multilib-testing]
#Include = /etc/pacman.d/mirrorlist-archlinuxarm

#[multilib]
#Include = /etc/pacman.d/mirrorlist-archlinuxarm

[alarm]
Include = /etc/pacman.d/mirrorlist-archlinuxarm
EOT

pacman-key --init
pacman-key --populate archlinuxarm
pacman -Sy

hwclock --systohc

pacman -Sy --needed --noconfirm --dbonly raspberrypi-bootloader raspberrypi-firmware

rc-update add ntpd default

#
# Configuration
#

echo -en 'armtix\narmtix' | passwd
userdel -r armtix

pacman -Rns --noconfirm sudo

rc-update del dhcpcd default
pacman -R --noconfirm dhcpcd-openrc

echo -e "\n\e[1m\e[1;32mArmtix has been successfully configured! It is NOT safe to reboot."
echo -e "\e[1m\e[1;32mDon't forget to change the root password and hostname, and to add a regular user for SSH."
echo -e "\e[1m\e[1;32mSetting up networking is left to you, dhcpcd and wpa_supplicant are installed."
echo -e "\e[1m\e[1;32mRebooting now will cause the device to become inaccessible due to disallowed SSH root login and the lack of network configuration."
echo -en "\e[0m"
