#! /bin/bash

set -e

function get_cmdline {
	sed -r 's/[[:alnum:]]+=/\n&/g' file | awk -F= '$1=="Var"{print $2}'
}

DRIVE=$1
PART_PREFIX=$2

if [[ -z "${DRIVE}" ]] | [[ -z "${PART_PREFIX}" ]]; then
	echo -e "\e[1m\e[1;31mUsage: mkcryptartix <drive> <partition prefix>\e[0m"
	exit 1
fi

TIMEZONE=$(get_cmdline tz)
ln -sf "/usr/share/zoneinfo/${TIMEZONE}" /etc/localtime
hwclock --systohc

sed -i "s/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/" /etc/locale.gen
locale-gen

cat <<EOT > /etc/locale.conf
export LANG="en_US.UTF-8"
export LC_COLLATE="C"
EOT

sed -i "s/HOOKS=(base udev autodetect modconf block filesystems keyboard fsck)/HOOKS=(base udev autodetect modconf block keyboard keymap encrypt filesystems fsck)/" /etc/mkinitcpio.conf

pacman -S --needed --noconfirm btrfs-progs grub os-prober device-mapper-openrc cryptsetup-openrc

BOOT_UUID=$(blkid -s UUID -o value ${PART_PREFIX}1)

dd bs=512 count=4 if=/dev/random of=/crypto_boot.bin iflag=fullblock
chmod 600 /crypto_boot.bin
echo "artix" | cryptsetup -q luksAddKey ${PART_PREFIX}1 /crypto_boot.bin

cat <<EOT >> /etc/conf.d/dmcrypt

target='boot_crypt'
source='/dev/disk/by-uuid/${BOOT_UUID}'
key='/crypto_boot.bin'
EOT

rc-update add dmcrypt boot

UUID=$(blkid -s UUID -o value ${PART_PREFIX}2)
sed -i "s/GRUB_CMDLINE_LINUX_DEFAULT=\"loglevel=3 quiet\"/GRUB_CMDLINE_LINUX_DEFAULT=\"loglevel=3 quiet cryptdevice=UUID=${UUID}:root_crypt\"/" /etc/default/grub
sed -i "s/#GRUB_ENABLE_CRYPTODISK=y/GRUB_ENABLE_CRYPTODISK=y/" /etc/default/grub
sed -i "s/GRUB_TERMINAL_INPUT=console/GRUB_TERMINAL_INPUT=at_keyboard/" /etc/default/grub

dd bs=512 count=4 if=/dev/random of=/crypto_keyfile.bin iflag=fullblock
chmod 600 /crypto_keyfile.bin
echo "artix" | cryptsetup -q luksAddKey ${PART_PREFIX}2 /crypto_keyfile.bin

sed -i "s/FILES=()/FILES=(\/crypto_keyfile.bin)/" /etc/mkinitcpio.conf

grub-install --recheck ${DRIVE}
grub-mkconfig -o /boot/grub/grub.cfg

mkinitcpio -p linux

# Enable GRUB to unlock /boot
CRYPTO_UUID=$(blkid -s UUID -o value ${PART_PREFIX}1 | tr -d -)
cat <<EOT > /boot/grub/grub-pre.cfg
set root=(memdisk)
set prefix=(\$root)/

terminal_input at_keyboard
keymap /keymap.gkb

set crypto_uuid=${CRYPTO_UUID}
cryptomount -u \$crypto_uuid

set root=crypto0
set prefix=(\$root)/grub

insmod normal
normal
EOT

pacman -S --needed --noconfirm libxkbcommon-x11 # XKB layouts

useradd ckbcomp
echo -en 'ckbcomp\nckbcomp' | passwd ckbcomp

git clone https://aur.archlinux.org/ckbcomp-bin.git /tmp/ckbcomp-bin
chown -R ckbcomp:ckbcomp /tmp/ckbcomp-bin
(cd /tmp/ckbcomp-bin && su ckbcomp -c 'makepkg')

userdel ckbcomp

cp -p /tmp/ckbcomp-bin/pkg/ckbcomp-bin/usr/bin/ckbcomp /usr/local/bin/ckbcomp

KEYMAP=$(get_cmdline keytable)

grub-kbdcomp -o /boot/grub/keymap.gkb ${KEYMAP}
(cd /boot/grub && tar cf memdisk.tar keymap.gkb)

grub-mkimage -p /boot/grub -c /boot/grub/grub-pre.cfg -o /boot/grub/i386-pc/core.img -O i386-pc -m /boot/grub/memdisk.tar disk biosdisk diskfilter luks2 part_msdos cryptodisk gcry_rijndael pbkdf2 gcry_sha256 ext2 memdisk tar at_keyboard keylayouts terminal
grub-bios-setup -d /boot/grub/i386-pc ${DRIVE}

pacman -Rns --noconfirm libxkbcommon-x11 # Not needed by all users

echo -en 'artix\nartix' | passwd

echo artix > /etc/hostname

cat <<EOT > /etc/hosts
# Static table lookup for hostnames.
# See hosts(5) for details.

127.0.0.1	localhost
127.0.1.1	artix.local	artix

# IPv6
::1		localhost	ip6-localhost	ip6-loopback
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
EOT

sed -i 's/hostname="localhost"/hostname="artix"/' /etc/conf.d/hostname

sed -i 's/keymap="us"/keymap="de"/' /etc/conf.d/keymaps

# Repositories
## Artix
cat <<EOT >> /etc/pacman.conf

#
# Custom
#

# Artix

[universe]
Server = https://universe.artixlinux.org/\$arch
Server = https://mirror1.artixlinux.org/universe/\$arch
Server = https://mirror.pascalpuffke.de/artix-universe/\$arch
Server = https://artixlinux.qontinuum.space/artixlinux/universe/os/\$arch
Server = https://mirror1.cl.netactuate.com/artix/universe/\$arch
Server = https://ftp.crifo.org/artix-universe/
EOT

## Arch
pacman -Sy --needed --noconfirm artix-archlinux-support

cat <<EOT >> /etc/pacman.conf

# Arch

#[testing]
#Include = /etc/pacman.d/mirrorlist-arch

[extra]
Include = /etc/pacman.d/mirrorlist-arch

#[community-testing]
#Include = /etc/pacman.d/mirrorlist-arch

[community]
Include = /etc/pacman.d/mirrorlist-arch

#[multilib-testing]
#Include = /etc/pacman.d/mirrorlist-arch

#[multilib]
#Include = /etc/pacman.d/mirrorlist-arch
EOT

pacman-key --populate archlinux
pacman -Sy

pacman -R --noconfirm sudo

rc-update add ntpd default

exit 0
