#! /bin/bash

set -e

ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
hwclock --systohc

sed -i "s/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/" /etc/locale.gen
locale-gen

cat <<EOT > /etc/locale.conf
export LANG="en_US.UTF-8"
export LC_COLLATE="C"
EOT

sed -i "s/HOOKS=(base udev autodetect modconf block filesystems keyboard fsck)/HOOKS=(base udev autodetect modconf block keyboard keymap encrypt filesystems fsck)/" /etc/mkinitcpio.conf

pacman -S --noconfirm btrfs-progs lvm2 cryptsetup grub os-prober device-mapper-openrc cryptsetup-openrc

UUID=$(blkid -s UUID -o value /dev/sda2)
sed -i "s/GRUB_CMDLINE_LINUX_DEFAULT=\"loglevel=3 quiet\"/GRUB_CMDLINE_LINUX_DEFAULT=\"loglevel=3 quiet cryptdevice=UUID=${UUID}:sda2_crypt\"/" /etc/default/grub

grub-install --recheck /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg

mkinitcpio -p linux

echo -en 'artix\nartix' | passwd

echo artix > /etc/hostname

cat <<EOT > /etc/hosts
# Static table lookup for hostnames.
# See hosts(5) for details.

127.0.0.1	localhost
127.0.1.1	artix.local	artix

# IPv6
::1		localhost	ip6-localhost	ip6-loopback
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
EOT

sed -i 's/hostname="localhost"/hostname="artix"/' /etc/conf.d/hostname

pacman -S --noconfirm dhclient

cat <<EOT >> /etc/conf.d/net

config_eth0="dhcp"
EOT

ln -s /etc/init.d/net.lo /etc/init.d/net.eth0
rc-update add net.eth0 default

sed -i 's/keymap="us"/keymap="de"/' /etc/conf.d/keymaps

# Repositories
## Artix
cat <<EOT >> /etc/pacman.conf

#
# Custom
#

# Artix

[universe]
Server = https://universe.artixlinux.org/\$arch
Server = https://mirror1.artixlinux.org/universe/\$arch
Server = https://mirror.pascalpuffke.de/artix-universe/\$arch
Server = https://artixlinux.qontinuum.space/artixlinux/universe/os/\$arch
Server = https://mirror1.cl.netactuate.com/artix/universe/\$arch
Server = https://ftp.crifo.org/artix-universe/
EOT

## Arch
pacman -Sy --noconfirm artix-archlinux-support

cat <<EOT >> /etc/pacman.conf

# Arch

#[testing]
#Include = /etc/pacman.d/mirrorlist-arch

[extra]
Include = /etc/pacman.d/mirrorlist-arch

#[community-testing]
#Include = /etc/pacman.d/mirrorlist-arch

[community]
Include = /etc/pacman.d/mirrorlist-arch

#[multilib-testing]
#Include = /etc/pacman.d/mirrorlist-arch

#[multilib]
#Include = /etc/pacman.d/mirrorlist-arch
EOT

pacman-key --populate archlinux
pacman -Sy

# Custom software
## Rm
pacman -R --noconfirm sudo

## Add
pacman -Sy --noconfirm vim ntpd
rc-update add ntpd default

exit 0
