#! /bin/bash

set -e

if [ "${UID}" != "0" ]; then
	echo "uefiinstall: requires root permissions"
	exit 1
fi

pacman -Sy
pacman -S --needed --noconfirm parted fzf

#
# Config questions
#

DRIVE=$1

if [ -z "${DRIVE}" ]; then
	DRIVE="/dev/$(lsblk | grep disk | fzf --disabled | awk '{print $1}')"
fi

if [[ "${DRIVE}" == "/dev/mmcblk"* ]] | [[ "${DRIVE}" == "/dev/nvme"* ]]; then
	PART_PREFIX="${DRIVE}p"
else
	PART_PREFIX="${DRIVE}"
fi

parted -s ${DRIVE} mklabel gpt
parted -s -a optimal ${DRIVE} mkpart primary fat32 0% 1GiB
parted -s -a optimal ${DRIVE} mkpart primary btrfs 1GiB 100%

mkfs.fat -F 32 ${PART_PREFIX}1 && fatlabel ${PART_PREFIX}1 ESP
mkfs.btrfs -f ${PART_PREFIX}2

mkdir /btrfs
mount -o compress=zstd ${PART_PREFIX}2 /btrfs
btrfs subvolume create /btrfs/boot
btrfs subvolume create /btrfs/root
umount /btrfs

mount -o compress=zstd,subvol=/root ${PART_PREFIX}2 /mnt
mkdir /mnt/boot
mount -o compress=zstd,subvol=/boot ${PART_PREFIX}2 /mnt/boot
mkdir /mnt/boot/efi
mount ${PART_PREFIX}1 /mnt/boot/efi

rc-service ntpd start

basestrap /mnt base openrc elogind-openrc vim man ntp-openrc git
basestrap /mnt linux linux-lts linux-firmware

artix-chroot /mnt bash -c "curl -fsSL https://raw.githubusercontent.com/HimbeerserverDE/artixinstall/main/mkuefi | sh -s -- ${DRIVE} ${PART_PREFIX}"

fstabgen -U /mnt >> /mnt/etc/fstab

umount -R /mnt

echo -e "\n\e[1m\e[1;32mArtix has been successfully installed! It is now safe to reboot."
echo -e "\e[1m\e[1;32mDon't forget to change the root password and hostname."
echo -e "\e[1m\e[1;32mSetting up networking is left to you, dhcpcd and wpa_supplicant are installed"
echo -e "\e[1m\e[1;32mincluding their OpenRC companion packages."
echo -en "\e[0m"
